### ISSUE TITLE
Android resource compilation failed -app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:7143: error: duplicate value for resource 'attr/pivotX' with config ''.

### ISSUE THREAD

**Issue by eudagraca** [akashandroid90/ImageLetterIcon#11]

**Comment by akashjaindev** [comment]
this is not lib dependent issue. You need to check your dependencies

**Comment by david-young-fax** [comment]
how to check? i have a similar issue like this. Here is my gradle:

    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.constraintlayout:constraintlayout:2.0.0-beta2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.3.0-alpha02'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0-alpha02'
    androidTestImplementation 'androidx.test:core:1.2.0'
    androidTestImplementation 'androidx.multidex:multidex-instrumentation:2.0.0'
    androidTestImplementation 'androidx.test:rules:1.3.0-alpha02'
    //implementation 'com.google.android.material:material:1.1.0-beta01'
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.recyclerview:recyclerview:1.1.0-beta05'
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'io.michaelrocks:libphonenumber-android:8.9.14'
    implementation 'com.github.joielechong:countrycodepicker:2.1.8'
    implementation 'cn.bingoogolapple:bga-alertcontroller:1.0.9@aar'
    implementation 'com.github.jkwiecien:EasyImage:1.3.1'
    implementation 'com.github.tajchert:nammu:1.2.1'
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'com.jakewharton:butterknife:8.8.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
    implementation 'info.androidhive:imagefilters:1.0.7'
    implementation 'com.karumi:dexter:4.1.0'
    implementation 'com.myhexaville:smart-image-picker:1.0.4'
    implementation 'com.theartofdev.edmodo:android-image-cropper:2.8.0'
    implementation 'androidx.room:room-runtime:2.2.0'
    annotationProcessor "androidx.room:room-compiler:2.2.0"
    implementation 'com.googlecode.libphonenumber:libphonenumber:7.2.2'
    implementation 'com.google.guava:guava:16+'
    implementation 'com.ndroid:cool-view:1.0'
    implementation 'com.squareup.retrofit2:retrofit:2.5.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.1.0'
    implementation 'com.github.f0ris.sweetalert:library:1.5.1'
    implementation 'com.google.firebase:firebase-core:17.0.0'
    implementation files('libs/universal-image-loader-1.9.5.jar')
