### ISSUE TITLE
Using Picasso or setImageResource with MaterialLetterIcon

### ISSUE THREAD

**Issue by ghost** [akashandroid90/ImageLetterIcon#6]
Hi,

I have the following use case:
- I have a list of contacts
- to add a contact, a "friend request" is sent
- in the adapter, I am using the viewHolder pattern

The flow:
- if a contact was added, but it hasn't been approved yet (the friend request is not accepted), I am displaying a local image using imageView.setImageResource()
- if the contact was added and was approved, I am loading it's picture from an url, using Picasso
- if the contact was added and was approved, but it has no profile picture (no url), I am showing 2 letters from it's name (imageView.setLetter(name))

I am using the same ImageView for all 3 cases. The ImageView is a MaterialLetterIcon.

The problem:
- the issue is related to view recycling. As I mentioned, I am using a viewHolder pattern and thus, I have to handle the if flow. For example: if url exists, then load into picasso, else, picasso needs a default placeholder and the letters need to be drawn. Setting a default placeholder or image resource doesn't work combined with the setLetter implementation. It sets the default placeholder but the letters are not drawn any more.

Example:
- After the list is loaded correctly (following the flow), when I background and foreground the app or scroll the list, the contacts that have the letter images have the resource image.

Solutions:
- I tried setting a null or transparent drawable on the first else (friend request accepted)
- in some cases, I only need the last 2 if's from the flow. I used 2 different imageViews, more exactly, an ImageView for Picasso, and the MaterialLetterIcon for the name, and I was handling their visibillity. This solution seems to work, but using 3 different imageViews for this case seems a bit overkill. Most likely there will be more if's added to the flow..

Version of lib:
- 1.2

What solution / approach do you suggest?

Thank you.

**Comment by akashjaindev** [comment]
hello

using more than one image view is not feasible. So you need to update view in your adapter for each position. I may need to see your adapter class so that I can figure out the issue.

Akash Jain

**Comment by ghost** [comment]
Hi,

I am not using more than one imageView, that was a solution I tried (to have multiple imageViews and handling their visibility).

I cannot provide the code, but I'll give you the image handling issue.
Note: MyPicassoTarget is setting the contact name (letters) in cause of url failure.


```
class ContactViewHolder extends RecyclerView.ViewHolder {
   public MaterialLetterIcon ivContact;
//more code
}

//more code, this snippet is when inflating the row
if (!contact.isAccepted()) {
   holder.ivContact.setShapeType(MaterialLetterIcon.SHAPE_NORMAL);
   holder.ivContact.setImageResource(R.drawable.my_drawable);
} else {
   if (contact.hasProfilePicture()) {
       MyPicassoTarget target = new MyPicassoTarget(holder.ivContact).setTextIcon(contact.getFullName());
       holder.ivContact.setTag(target);
       Picasso.with(holder.ivContact.getContext()).load(contact.getProfileUrl()).into(target);
   } else {
       holder.ivContact.setShapeColor(ContextCompat.getColor(holder.ivContact.getContext(), R.color.my_color));
       holder.ivContact.setLetter(contact.getFullName());
   }
```

**Comment by akashjaindev** [comment]
hello
you can use textdrawble as an placeholder for showing for showing drawable while loading image from picasso.

**Comment by ghost** [comment]
Hi,

Thanks. But what should I use the case without Picasso? This is my main issue now. I'll simplify the code:

```
if (!contact.isAccepted()) {
   holder.ivContact.setShapeType(MaterialLetterIcon.SHAPE_NORMAL);
   holder.ivContact.setImageResource(R.drawable.my_drawable);
} else {
       holder.ivContact.setShapeColor(ContextCompat.getColor(holder.ivContact.getContext(), R.color.my_color));
       holder.ivContact.setLetter(contact.getFullName());
   }
```

**Comment by akashjaindev** [comment]
hello i haven't find any such case but i will check and if there is any issue i will update you.
One more thing are you changing shape of imageview according to your condition since as i am seeing you have change shape type only when contact is not accepted.

Akash Jain

**Comment by akashjaindev** [comment]
hello
i have tried in a sample but i am not getting any such problem. Make sure you are using latest library using: compile 'com.github.akashandroid90:imageletter:1.8@aar'
Let me know if there is still error.
Akash Jain

**Comment by ghost** [comment]
Hi,
I tried using the latest lib you mentioned, still happens. 
I noticed you mention about the shape changing, I will try and see if this is the cause. The shape should be the same, no matter the condition.

**Comment by akashjaindev** [comment]
ok. let me know if there is still any issue.
