### ISSUE TITLE
Android Studio 3.0, error project build, " duplicate value for resource 'attr/tint' with config'" "

### ISSUE THREAD

**Issue by duanniston** [akashandroid90/ImageLetterIcon#7]
Android Studio 3.0, error project build, " duplicate value for resource 'attr/tint' with config'" " with this library.

**Comment by akashjaindev** [comment]
ok we will check and figure out the issue. And update you soon

**Comment by akashjaindev** [comment]
check you gradle version. i have tried but i am not getting any error. You can check by cleaning the project.

**Comment by ibcurly** [comment]
Same issue here, cleaned project
gradle version 3.0

**Comment by akashjaindev** [comment]
please update your gradle version and try again. I have updated my studio and and gradle version and i am not facing any problem at all.

**Comment by ohenepee** [comment]
I don't think this is a gradle version issue... I am using Android Studio 3.0 with Gradle Plugin Version 3.0.0 (which uses Gradle 4.1+) **THE LATEST**. And like everyone complaining here I am getting this same issue. Just rename whatever attribute you've named `tint` to something like `libTint` or `lib_tint` or even more obscure `ili_lib_tint` so the issue can be resolved. I really want to use this lib and not look else where, please.

This is the xml element causing the issue https://github.com/akashandroid90/ImageLetterIcon/blob/de07bbefa5f43c18c65f0bb2d2dab12d9cafefe0/imageletter/src/main/res/values/attrs.xml#L20

**Comment by akashjaindev** [comment]
files updated and pushed on jcenter just change library version to 1.14

**Comment by Katlego-K** [comment]
Guys, I get this Error "Error:(253, 5) error: duplicate value for resource 'attr/textColorError' with config ''. Please assist.

**Comment by Katlego-K** [comment]
![image](https://user-images.githubusercontent.com/34712841/34209422-c4492946-e59a-11e7-992d-1996099588ca.png)
Please Assist.

**Comment by akashjaindev** [comment]
i don't think this is library issue since we haven't use this attribute. Can you please check other libraries you are using.

**Comment by Katlego-K** [comment]
@akashandroid90 ,Ok cool let me check them and i will get back to you.

**Comment by Katlego-K** [comment]
@akashandroid90 , I still get the same error message & my libraries do match. See below plz help

![image](https://user-images.githubusercontent.com/34712841/34297486-17f8f13e-e721-11e7-8ac6-8543eb5d4926.png)

**Comment by akashjaindev** [comment]
As you can see in your attached screenshot you havent use imagelettericon lib. And as i am recognising this issue is regarding your appcompat lib version. Make sure you are using same version of it.

**Comment by Katlaped** [comment]
Is the same, see below 👍 
![image](https://user-images.githubusercontent.com/34712841/34401170-7e4311fc-eba1-11e7-9c36-a8b5275a9747.png)

**Comment by parasnath** [comment]
I am also getting same error as error: duplicate value for resource 'attr/track' with config ''. any one have a solution

**Comment by akashjaindev** [comment]
please check you libs which you have used in app. This issue is not related with our library

**Comment by xuanguofeng** [comment]
Some attributes of values/attrs should be causing errors
